### ISSUE TITLE
Not supported on nVidia Kepler GPU's?

### ISSUE THREAD

**Issue by addeps3** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#117]
path to binary was was exported with: `export LD_LIBRARY_PATH=/home/myusername/build/RadeonProRender-Baikal/builddirectory/bin/:${LD_LIBRARY_PATH}
`

./BaikalStandalone 
Running on devices: 
0: GeForce GTX 770
OpenGL interop mode enabled
Cannot open file [../Resources/CornellBox/orig.objm]

./BaikalTest 
[==========] Running 55 tests from 7 test cases.
[----------] Global test environment set-up.
[----------] 1 test from InternalTest
[ RUN      ] InternalTest.Distribuiton1D
[       OK ] InternalTest.Distribuiton1D (0 ms)
[----------] 1 test from InternalTest (0 ms total)

[----------] 2 tests from BasicTest
[ RUN      ] BasicTest.Init
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] BasicTest.Init (206 ms)
[ RUN      ] BasicTest.RenderTestScene
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] BasicTest.RenderTestScene (160 ms)
[----------] 2 tests from BasicTest (367 ms total)

[----------] 4 tests from CameraTest
[ RUN      ] CameraTest.Camera_FocalLength
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] CameraTest.Camera_FocalLength (161 ms)
[ RUN      ] CameraTest.Camera_SensorSize
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] CameraTest.Camera_SensorSize (161 ms)
[ RUN      ] CameraTest.Camera_Aperture
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] CameraTest.Camera_Aperture (160 ms)
[ RUN      ] CameraTest.Camera_FocusDistance
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] CameraTest.Camera_FocusDistance (157 ms)
[----------] 4 tests from CameraTest (639 ms total)

[----------] 16 tests from LightTest
[ RUN      ] LightTest.Light_PointLight
Compilation failed!
Dumping source to file:monte_carlo_renderer.cl.failed
/home/adam/build/RadeonProRender-Baikal/BaikalTest/light.h:81: Failure
Expected: m_renderer->Render(scene) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] LightTest.Light_PointLight (637 ms)
[ RUN      ] LightTest.Light_PointLightMany
Compilation failed!
Dumping source to file:monte_carlo_renderer.cl.failed
/home/adam/build/RadeonProRender-Baikal/BaikalTest/light.h:154: Failure
Expected: m_renderer->Render(scene) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] LightTest.Light_PointLightMany (261 ms)
[ RUN      ] LightTest.Light_DirectionalLight
Compilation failed!
Dumping source to file:monte_carlo_renderer.cl.failed
/home/adam/build/RadeonProRender-Baikal/BaikalTest/light.h:201: Failure
Expected: m_renderer->Render(scene) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] LightTest.Light_DirectionalLight (262 ms)
[ RUN      ] LightTest.Light_SpotLight
Compilation failed!
Dumping source to file:monte_carlo_renderer.cl.failed
/home/adam/build/RadeonProRender-Baikal/BaikalTest/light.h:276: Failure
Expected: m_renderer->Render(scene) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] LightTest.Light_SpotLight (273 ms)
[ RUN      ] LightTest.Light_AreaLight
Compilation failed!
Dumping source to file:monte_carlo_renderer.cl.failed
/home/adam/build/RadeonProRender-Baikal/BaikalTest/light.h:328: Failure
Expected: m_renderer->Render(scene) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] LightTest.Light_AreaLight (270 ms)
[ RUN      ] LightTest.Light_DirectionalAndAreaLight
Compilation failed!
Dumping source to file:monte_carlo_renderer.cl.failed
/home/adam/build/RadeonProRender-Baikal/BaikalTest/light.h:379: Failure
Expected: m_renderer->Render(scene) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] LightTest.Light_DirectionalAndAreaLight (265 ms)
[ RUN      ] LightTest.Light_PointAndAreaLight
Compilation failed!
Dumping source to file:monte_carlo_renderer.cl.failed
/home/adam/build/RadeonProRender-Baikal/BaikalTest/light.h:429: Failure
Expected: m_renderer->Render(scene) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] LightTest.Light_PointAndAreaLight (273 ms)
[ RUN      ] LightTest.Light_SpotAndAreaLight
Compilation failed!
Dumping source to file:monte_carlo_renderer.cl.failed
/home/adam/build/RadeonProRender-Baikal/BaikalTest/light.h:486: Failure
Expected: m_renderer->Render(scene) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] LightTest.Light_SpotAndAreaLight (272 ms)
[ RUN      ] LightTest.Light_EmissiveSphere
Compilation failed!
Dumping source to file:monte_carlo_renderer.cl.failed
/home/adam/build/RadeonProRender-Baikal/BaikalTest/light.h:536: Failure
Expected: m_renderer->Render(scene) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] LightTest.Light_EmissiveSphere (281 ms)
[ RUN      ] LightTest.Light_DirectionalAndEmissiveSphere
Compilation failed!
Dumping source to file:monte_carlo_renderer.cl.failed
/home/adam/build/RadeonProRender-Baikal/BaikalTest/light.h:591: Failure
Expected: m_renderer->Render(scene) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] LightTest.Light_DirectionalAndEmissiveSphere (285 ms)
[ RUN      ] LightTest.Light_ImageBasedLight
unknown file: Failure
C++ exception with description "Can't load ../Resources/Textures/studio015.hdr image" thrown in the test body.
[  FAILED  ] LightTest.Light_ImageBasedLight (256 ms)
[ RUN      ] LightTest.Light_ImageBasedLightAndLightChanging
unknown file: Failure
C++ exception with description "Can't load ../Resources/Textures/studio015.hdr image" thrown in the test body.
[  FAILED  ] LightTest.Light_ImageBasedLightAndLightChanging (255 ms)
[ RUN      ] LightTest.Light_ImageBasedLightAndEmissiveQuad
unknown file: Failure
C++ exception with description "Can't load ../Resources/Textures/studio015.hdr image" thrown in the test body.
[  FAILED  ] LightTest.Light_ImageBasedLightAndEmissiveQuad (244 ms)
[ RUN      ] LightTest.Light_IblReflectionOverride
unknown file: Failure
C++ exception with description "Can't load ../Resources/Textures/studio015.hdr image" thrown in the test body.
[  FAILED  ] LightTest.Light_IblReflectionOverride (252 ms)
[ RUN      ] LightTest.Light_IblRefractionOverride
unknown file: Failure
C++ exception with description "Can't load ../Resources/Textures/studio015.hdr image" thrown in the test body.
[  FAILED  ] LightTest.Light_IblRefractionOverride (255 ms)
[ RUN      ] LightTest.Light_IblTransparencyOverride
unknown file: Failure
C++ exception with description "Can't load ../Resources/Textures/studio015.hdr image" thrown in the test body.
[  FAILED  ] LightTest.Light_IblTransparencyOverride (241 ms)
[----------] 16 tests from LightTest (4583 ms total)

[----------] 19 tests from MaterialTest
[ RUN      ] MaterialTest.Material_Diffuse
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_Diffuse (158 ms)
[ RUN      ] MaterialTest.Material_Reflect
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_Reflect (158 ms)
[ RUN      ] MaterialTest.Material_MicrofacetGGX
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_MicrofacetGGX (163 ms)
[ RUN      ] MaterialTest.Material_MicrofacetBeckmann
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_MicrofacetBeckmann (164 ms)
[ RUN      ] MaterialTest.Material_Refract
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_Refract (156 ms)
[ RUN      ] MaterialTest.Material_MicrofacetRefractGGX
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_MicrofacetRefractGGX (159 ms)
[ RUN      ] MaterialTest.Material_MicrofacetRefractBeckmann
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_MicrofacetRefractBeckmann (163 ms)
[ RUN      ] MaterialTest.Material_Translucent
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_Translucent (163 ms)
[ RUN      ] MaterialTest.Material_DiffuseAndMicrofacet
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_DiffuseAndMicrofacet (162 ms)
[ RUN      ] MaterialTest.Material_DiffuseAndTransparency
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_DiffuseAndTransparency (156 ms)
[ RUN      ] MaterialTest.Material_RefractionAndMicrofacet
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_RefractionAndMicrofacet (163 ms)
[ RUN      ] MaterialTest.Material_RefractionAndDoubleMicrofacet
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_RefractionAndDoubleMicrofacet (163 ms)
[ RUN      ] MaterialTest.Material_MixRefractAndMicrofacet
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_MixRefractAndMicrofacet (164 ms)
[ RUN      ] MaterialTest.Material_MixDiffuseAndMicrofacet
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_MixDiffuseAndMicrofacet (163 ms)
[ RUN      ] MaterialTest.Material_MixDiffuseAndTransparencyMask
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_MixDiffuseAndTransparencyMask (164 ms)
[ RUN      ] MaterialTest.Material_VolumeScattering
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_VolumeScattering (157 ms)
[ RUN      ] MaterialTest.Material_VolumeAbsorption
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_VolumeAbsorption (164 ms)
[ RUN      ] MaterialTest.Material_VolumeEmission
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_VolumeEmission (163 ms)
[ RUN      ] MaterialTest.Material_PhaseFunction
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] MaterialTest.Material_PhaseFunction (163 ms)
[----------] 19 tests from MaterialTest (3066 ms total)

[----------] 8 tests from AovTest
[ RUN      ] AovTest.Aov_WorldPosition
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] AovTest.Aov_WorldPosition (163 ms)
[ RUN      ] AovTest.Aov_WorldNormal
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] AovTest.Aov_WorldNormal (162 ms)
[ RUN      ] AovTest.Aov_ShadingNormal
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] AovTest.Aov_ShadingNormal (162 ms)
[ RUN      ] AovTest.Aov_Tangent
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] AovTest.Aov_Tangent (162 ms)
[ RUN      ] AovTest.Aov_Bitangent
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] AovTest.Aov_Bitangent (162 ms)
[ RUN      ] AovTest.Aov_Albedo
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] AovTest.Aov_Albedo (161 ms)
[ RUN      ] AovTest.Aov_Uv
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] AovTest.Aov_Uv (157 ms)
[ RUN      ] AovTest.Aov_Visibility
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] AovTest.Aov_Visibility (157 ms)
[----------] 8 tests from AovTest (1287 ms total)

[----------] 5 tests from TestScenesTest
[ RUN      ] TestScenesTest.TestScenes_CornellBox
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] TestScenesTest.TestScenes_CornellBox (162 ms)
[ RUN      ] TestScenesTest.TestScenes_Sponza
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] TestScenesTest.TestScenes_Sponza (163 ms)
[ RUN      ] TestScenesTest.TestScenes_Classroom
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] TestScenesTest.TestScenes_Classroom (159 ms)
[ RUN      ] TestScenesTest.TestScenes_Rungholt
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] TestScenesTest.TestScenes_Rungholt (162 ms)
[ RUN      ] TestScenesTest.TestScenes_San_Miguel
/home/adam/build/RadeonProRender-Baikal/BaikalTest/basic.h:124: Failure
Expected: LoadTestScene() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] TestScenesTest.TestScenes_San_Miguel (163 ms)
[----------] 5 tests from TestScenesTest (809 ms total)

[----------] Global test environment tear-down
[==========] 55 tests from 7 test cases ran. (10751 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 54 tests, listed below:
[  FAILED  ] BasicTest.Init
[  FAILED  ] BasicTest.RenderTestScene
[  FAILED  ] CameraTest.Camera_FocalLength
[  FAILED  ] CameraTest.Camera_SensorSize
[  FAILED  ] CameraTest.Camera_Aperture
[  FAILED  ] CameraTest.Camera_FocusDistance
[  FAILED  ] LightTest.Light_PointLight
[  FAILED  ] LightTest.Light_PointLightMany
[  FAILED  ] LightTest.Light_DirectionalLight
[  FAILED  ] LightTest.Light_SpotLight
[  FAILED  ] LightTest.Light_AreaLight
[  FAILED  ] LightTest.Light_DirectionalAndAreaLight
[  FAILED  ] LightTest.Light_PointAndAreaLight
[  FAILED  ] LightTest.Light_SpotAndAreaLight
[  FAILED  ] LightTest.Light_EmissiveSphere
[  FAILED  ] LightTest.Light_DirectionalAndEmissiveSphere
[  FAILED  ] LightTest.Light_ImageBasedLight
[  FAILED  ] LightTest.Light_ImageBasedLightAndLightChanging
[  FAILED  ] LightTest.Light_ImageBasedLightAndEmissiveQuad
[  FAILED  ] LightTest.Light_IblReflectionOverride
[  FAILED  ] LightTest.Light_IblRefractionOverride
[  FAILED  ] LightTest.Light_IblTransparencyOverride
[  FAILED  ] MaterialTest.Material_Diffuse
[  FAILED  ] MaterialTest.Material_Reflect
[  FAILED  ] MaterialTest.Material_MicrofacetGGX
[  FAILED  ] MaterialTest.Material_MicrofacetBeckmann
[  FAILED  ] MaterialTest.Material_Refract
[  FAILED  ] MaterialTest.Material_MicrofacetRefractGGX
[  FAILED  ] MaterialTest.Material_MicrofacetRefractBeckmann
[  FAILED  ] MaterialTest.Material_Translucent
[  FAILED  ] MaterialTest.Material_DiffuseAndMicrofacet
[  FAILED  ] MaterialTest.Material_DiffuseAndTransparency
[  FAILED  ] MaterialTest.Material_RefractionAndMicrofacet
[  FAILED  ] MaterialTest.Material_RefractionAndDoubleMicrofacet
[  FAILED  ] MaterialTest.Material_MixRefractAndMicrofacet
[  FAILED  ] MaterialTest.Material_MixDiffuseAndMicrofacet
[  FAILED  ] MaterialTest.Material_MixDiffuseAndTransparencyMask
[  FAILED  ] MaterialTest.Material_VolumeScattering
[  FAILED  ] MaterialTest.Material_VolumeAbsorption
[  FAILED  ] MaterialTest.Material_VolumeEmission
[  FAILED  ] MaterialTest.Material_PhaseFunction
[  FAILED  ] AovTest.Aov_WorldPosition
[  FAILED  ] AovTest.Aov_WorldNormal
[  FAILED  ] AovTest.Aov_ShadingNormal
[  FAILED  ] AovTest.Aov_Tangent
[  FAILED  ] AovTest.Aov_Bitangent
[  FAILED  ] AovTest.Aov_Albedo
[  FAILED  ] AovTest.Aov_Uv
[  FAILED  ] AovTest.Aov_Visibility
[  FAILED  ] TestScenesTest.TestScenes_CornellBox
[  FAILED  ] TestScenesTest.TestScenes_Sponza
[  FAILED  ] TestScenesTest.TestScenes_Classroom
[  FAILED  ] TestScenesTest.TestScenes_Rungholt
[  FAILED  ] TestScenesTest.TestScenes_San_Miguel

54 FAILED TESTS

**Comment by yozhijk** [comment]
You are running the test from wrong working directory, please follow instructions in README file.

**Comment by addeps3** [comment]
![screenshot from 2018-04-05 16-48-50](https://user-images.githubusercontent.com/18384170/38373376-6f1e2a84-38f1-11e8-9dfb-c139e07d7e9c.png)
