### ISSUE TITLE
2 issues for BaikalStandalone

### ISSUE THREAD

**Issue by harokyang** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#131]
first issue: 
MSVCP110D.DLL and MSVCR110D.DLL missing if BaikalStandalone built with Debug
could be related to OpenImageIO
unless VS 2012 installed, there is no way to get those debug version dlls from redistribution pack

second issue:
if BaikalStandalone is running on a laptop, 2 platforms could be created
each one contains a device, the integrated and the discrete GPU
When OpenCL try to create a context with interop supported, if it failed on the first device, an exception will be thrown
The exception will be caught and assume no more interop supported even though the second device has not been tried
In my case because the integrated GPU(Intel HD Graphics 620) will always be labeled as the first device, my discrete one(R5 M430) can never be used

**Comment by SimonDanisch** [comment]
you can run baikalstandalone with `platform 1` for your discrete gpu!

**Comment by harokyang** [comment]
it worked, thx
