### ISSUE TITLE
I can not render with Orthographic Camera when i specify it with arguments

### ISSUE THREAD

**Issue by lumx** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#133]
I started trying different camera types and it seems that Orthographic camera is not working. I just get a grey wall that is the default material in Cornell Box
![image](https://user-images.githubusercontent.com/3934798/39015555-02d978f0-441e-11e8-9100-0bb66e42ad45.png)

**Comment by yozhijk** [comment]
Hi @lumx ,

It is correct behavior for an ortho camera with its default settings. Note, that it is using parallel projection and your image plane is very small by default in world space (like 36x24mm), so it only projects a small piece of the back wall. If you make an image plane larger in world space, like for example 4m, the whole Cornell Box is going to fit in there. Below is an image with with image plane size = 4m and ortho camera (BaikalStandalone64 -ssx 4 -ct orthographic)

![image](https://user-images.githubusercontent.com/4111901/39055534-cbb9c0cc-44b4-11e8-8620-63019c946331.png)

**Comment by lumx** [comment]
@yozhijk Thank you for you quick reply. After going through the code in more detail I saw what I missed
