### ISSUE TITLE
Fisheye effect on flat surface refraction

### ISSUE THREAD

**Issue by harokyang** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#142]
I made some glass doors, and set the glass material to kIdealRefraction + kIdealReflection
But the refraction effect seems broken
everything I see through the glass is fisheyed, especially when the incidence angle is large
The only workaround is to enlarge the model to make the glass thicker

The Thin flag of material has no use on this issue

**Comment by harokyang** [comment]
After some research, I found the root of the issue
It is because of the double glasses combination
two glasses stay close to each other, only a very small gap between each them

The ray pass through the first glass then the second one, but somehow the number of entry and exit glass surface didn't match
So after leaving the second glass, the outgoing angle didn't restored to the first incidence angle, and made a very strange fisheye lens effect

**Comment by yozhijk** [comment]
Yes, that's an issue with refractive materials, you need to make sure the object has some volume and sometimes ray epsilon prevents from doing that.

**Comment by harokyang** [comment]
Found an easy fix for that issue,
Just lower the value of CRAZY_LOW_DISTANCE in common.cl
Perhaps we can make it a programmable value
