### ISSUE TITLE
Build issues on Ubuntu 18.04. Repeatedly facing the same issue.

### ISSUE THREAD

**Issue by faisal432** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#146]
Facing issues while building Radeon Prorender baikal on AMD platform on Ubuntu 18.04. Please find the log attached for the same.

[libimage.log](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal/files/2011766/libimage.log)

**Comment by yozhijk** [comment]
Fixed here: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal/commit/a07eb9a5f3b95036d55e8b02ca2711bb72806b81

**Comment by yozhijk** [comment]
Closing, seems solved
