### ISSUE TITLE
What is the technical foundation of this limitation of the Blender Plugin integration ?

### ISSUE THREAD

**Issue by Cru-N-cher** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#16]
Hardware:
Runs on both GPUs and CPUs. OpenCL 1.2 required for GPUs
AMD graphics cards are recommended
For non-AMD OpenCL 1.2 cards, **Windows 10 is required**

**Comment by bsavery** [comment]
Hey there.  If you're looking for blender plugin specific questions it might be best to post them here:  http://support.radeonprorender.com/support/home

What OS are you on?

**Comment by yozhijk** [comment]
Closing the issue (use Blender forum for Blender-related questions)
