### ISSUE TITLE
After Baikal Split from Radeon rays Compile break

### ISSUE THREAD

**Issue by Kingbadger3d** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#2]
Maybe im having a brain fart, But now that Baikal and Radeon Rays are separated I cant for the Love of god get things to compile correctly. Could you Please add a Help Doc and How to compile the 2 separate repos now to make one working project. Cheers J

**Comment by spacekookie** [comment]
Not a project maintainer or developer.

But what compilation issues are you getting and on what platform?

**Comment by yozhijk** [comment]
@Kingbadger3d I have added build steps into README.md doc
