### ISSUE TITLE
"Scene has not been compiled" while using RPR API

### ISSUE THREAD

**Issue by nidin** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#24]
While using RPR API **rprContextRender** always hitting error "Scene has not been compiled".
Looks like scene is not committing.

![image](https://user-images.githubusercontent.com/198246/29530573-b7a9105c-86a4-11e7-8be2-8e7d4d336b9c.png)

The same issue happens in **RprTest**!

<img width="900" alt="screen shot 2017-08-21 at 19 08 46" src="https://user-images.githubusercontent.com/198246/29530474-3c5745a4-86a4-11e7-961a-a4addda5e963.png">

**Comment by beasterio** [comment]
CompileScene() call was missing.
Should be ok on current master :-)

**Comment by nidin** [comment]
😄  
I manually added CompileScene and it was working but i guess there are some other issues with simple render test, it was generating black images. anyway i will test with latest master. 
Thanks.

**Comment by beasterio** [comment]
yeap, rpr part was a bit outdated.
Fix for SimpleRenderTest is in pull request.

**Comment by yozhijk** [comment]
Closing as resolved
