### ISSUE TITLE
premake5 linux

### ISSUE THREAD

**Issue by bsavery** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#27]
Minor issue but the premake5 for linux is linked against libssl.so.1.0.0. Which is deprecated on newer linux distros (redhat and centos).  I simply replaced the binary with the one from their latest build and it worked fine without the libssl dependency.

**Comment by yozhijk** [comment]
Could you create a pull request containing your change?

**Comment by bsavery** [comment]
Will do.

**Comment by yozhijk** [comment]
Build on CentOS is now working.
