### ISSUE TITLE
Running on intel i5-4590 failed.

### ISSUE THREAD

**Issue by FishOrBear** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#29]
I tried debugging the program, and when calling ```ConfigManager :: CreateConfigs``` raised an error.

After the code used interop = false.

But after that, the program is running on the white screen.

So I changed the code a little bit.

in ```config_manager.cpp```
line 58
```for (int i = platforms.size () - 1; i> = 0; i--)```

Prioritize the GPU.

So the program can be opened.

**Comment by FurryFur** [comment]
I had the same problem, thanks for the quick fix. I'm running an i5-4690K.

**Comment by FurryFur** [comment]
I can only seem to get it to work on 1 GPU for some reason as well.

**Comment by yozhijk** [comment]
@FurryFur , could you please attach the output of clinfo command for  your system?

**Comment by yozhijk** [comment]
Closing as obsolete
