### ISSUE TITLE
Can't run Baikal binaries on Linux

### ISSUE THREAD

**Issue by spacekookie** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#33]
Running Ubuntu 16.04. I built RadeonRays (as the submodule) first. Compiling went successfully. And all the files seem to be there:

```
 🚀  (tempest) ~/D/RadeonProRender-Baikal> tree Bin/
Bin/
└── Release
    └── x64
        ├── BaikalStandalone64
        ├── BaikalTest64
        ├── libBaikal64.a
        ├── libCalc64.a
        ├── libCLW64.a
        ├── libGtest64.a
        ├── libRadeonRays64.so -> libRadeonRays64.so.
        └── libRadeonRays64.so.
```

When trying to run `BaikalTest64` it's saying:

```
Bin/Release/x64/BaikalTest64: error while loading shared libraries: libRadeonRays64.so.: cannot open shared object file: No such file or directory
```

The same thing happens when running the binary from the directory it's in. Where exactly is it looking for the so? Because it's right next to it there...

**Comment by yozhijk** [comment]
Try adding ../Bin/Release/x64 into your LD_LIBRARY_PATH env variable and run it from BaikalTest

**Comment by yozhijk** [comment]
Closing as obsolete
