### ISSUE TITLE
g_* - undeclared identifier (Windows, vs2015)

### ISSUE THREAD

**Issue by m10914** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#48]
Probably me being stupid again, but I'm getting

```1>CLWParallelPrimitives.cpp(49): error C2065: 'g_CLW_opencl': undeclared identifier
2>src\accelerator\hlbvh.cpp(106): error C2065: 'g_build_hlbvh_opencl': undeclared identifier
2>src\intersector\intersector_hlbvh.cpp(109): error C2065: 'g_intersect_hlbvh_stack_opencl': undeclared identifier
2>src\intersector\intersector_skip_links.cpp(113): error C2065: 'g_intersect_bvh2_skiplinks_opencl': undeclared identifier
2>src\intersector\intersector_bittrail.cpp(119): error C2065: 'g_intersect_bvh2_bittrail_opencl': undeclared identifier
```

and a couple more...
What am I doing wrong? Wrong OpenCL SDK version?

**Comment by yozhijk** [comment]
Hi @m10914 ,

What is the python version you are using? Is it accessible from PATH env variable? Seems like kernel baking process failed. Could you attach your premake output?

**Comment by romanlarionov** [comment]
@yozhijk Do we need python 3x or 2x installed? I seem to be getting the same errors.

**Comment by Kingbadger3d** [comment]
@m10914 I had the same issue after doing fresh install of win10, I bet you used powershell to create the vs files, Instead use the cmd tool. press windows key with R, type cmd into the run window bar.

now run premake from here like you would normaly, load the sln file and should compile fine, weird that powershell is screwing up like that.

**Comment by yozhijk** [comment]
@m10914 @romanlarionov python 2.x is required, we are using cygwin python for our build server

**Comment by romanlarionov** [comment]
@yozhijk @m10914 

After coming back to this topic, I've found the reason for the error generated in the above snippet. The "stringify.py" file does not handle a global path with spaces well and errors.

i.e. C:/Developer/Ray Tracing/RadeonProRender-Baikal > C:/Developer/Ray_Tracing/RadeonProRender-Baikal

Fixed all of my issues.

**Comment by yozhijk** [comment]
Ah, ok, closing the issue then
