### ISSUE TITLE
Missing source codes for RprSupport

### ISSUE THREAD

**Issue by akazantsev** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#55]
Hello, I've wanted to use ProRender 1.4.0 for blender

https://pro.radeon.com/en/software/prorender/blender/

But I've found that libraries in that plugin aren't suitable to be run on my linux system(Archlinux)

- libRadeonProRender64.so
- libRprSupport64.so

It looked that I could build those from this repository and replace them. So I configured project with this command
`
Tools/premake/linux64/premake5 gmake --rpr --gltf`

I was unable to compile it due dependency of "gltf" option, which requires RprSupport library. Which is in binary form only for windows. Could you publish it's source code in this repository?

**Comment by fo-fo** [comment]
The renderer in this repository is not the same one that is used in the "Radeon ProRender for Blender" plugin. The last I checked the RPR API implementation in this version is missing some functions required by the Blender plugin interface code, so I don't think you can replace the library, even if you get it to build.

**Comment by bsavery** [comment]
Hey @akazantsev I can probably help you.  What is the issue when you said the libraries aren't suitable for your archlinux distro?  If you run LDD on them I'm assuming you're missing some dependencies?  We only officially support Ubuntu and Redhat/Centos for the blender plugin.  Either way if you want to connect on https://discord.gg/Xy9wUFj . We can help out there.

**Comment by yozhijk** [comment]
Closing this one. Baikal does not support building vs Blender plugin atm. Please contact @bsavery  for more information.
