### ISSUE TITLE
3rd Party Debug Binaries

### ISSUE THREAD

**Issue by romanlarionov** [GPUOpen-LibrariesAndSDKs/RadeonProRender-Baikal#97]
It would be really helpful if the debug versions of the dlls included in the `3rdparty` directory were included.

**Comment by yozhijk** [comment]
We are not linking our debug config against debug version, except OpenImageIO (which is in the repo). What debug lib would you like to see?

**Comment by romanlarionov** [comment]
ohh sorry. I forgot to close. I think I actually had issues with not having some MSVC 2012 debug libraries installed.. Even though I use 2015.

Nothing wrong with your 3rd party stuff.

**Comment by claforte** [comment]
In case this is helpful to others, I ran into the same issue. The problem is that OpenImageIOD.dll is dynamically linked against the debug MSCV2012 runtime, i.e. MSVCP110D.dll and MSVCR110D.dll. Since rebuilding OIIO is daunting, I tried to work around the issue by manually renaming OPenImageIO.[dll/lib] to overwrite OpenImageIOD.[dll/lib]. BaikalStandalone.exe now starts but I ran into other issues ("bad allocation" at start-up).

**Comment by harokyang** [comment]
Install VS 2012
extract MSVCP110D.DLL and MSVCR110D.DLL, place them in project as 3rd party librarys
Modify CMakelists.txt to copy those files
uninstall VS 2012

That's my solution

**Comment by romanlarionov** [comment]
^^ Installing VS 2012 was my solution. You can't install the redistributables from the VS website because they don't include the debug version: MSVCP110D.dll.

**Comment by claforte** [comment]
No, this isn't a solution. You should redistribute those DLLs in your 3rdparty folder. That would be a real solution, that doesn't involve every other Windows developer bumping into that problem, wasting time trying to figure out what's wrong, then wasting an hours installing a 6-years old software. You should re-open this issue until someone commits the DLLs in the folder.

**Comment by claforte** [comment]
As further proof that installing Visual Studio 2012 isn't a solution... I tried to do so this morning, and found that no free version of VS2012 is available anymore. No "Express" or "Community Edition".

I would rather not download DLLs from shady web sites. Can anyone please commit the official DLLs in 3rdparty? Thanks a lot.

**Comment by romanlarionov** [comment]
First off, I'm not involved in this project so I'm not going to commit anything.

Second, you can totally download VS 2012 from microsoft's website: https://www.visualstudio.com/vs/older-downloads/

**Comment by claforte** [comment]
Thank you Roman, I will try to do that.
